### ISSUE TITLE
OptionPageCS project doesn't build because of a missing file

### ISSUE THREAD

**Issue by maxperga** [Microsoft/VSSDK-Extensibility-Samples#100]
### Installed products
- Visual Studio: Enterprise 2017 Version 15.3.5

### Description
OptionPageCS project doesn't build because of a missing file.

### Steps to recreate
1. Open OptionPageCS project
2. Try to build it.

### Current behavior
1>------ Build started: Project: OptionsPageCS, Configuration: Debug Any CPU ------
1>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(711,5): error BG1002: File 'Example.OptionsPage2.png' cannot be found.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ========== 

### Expected behavior
Build succeeds.

**Comment by StephanieSu** [comment]
Fixed.  Thanks for reporting!
