### ISSUE TITLE
how can i get default language services in VSIXProject?

### ISSUE THREAD

**Issue by hq1993922** [microsoft/VSSDK-Extensibility-Samples#117]
### Installed products
Visual Studio 2017
VSSDK
### Description
I am developing a VSIXProject for my assembly.I want to highlight the function my assembly implement and show a tooltip when mouse hover. And search all references  of my assembly from solution. 
Can i get code references,namespace,classname or other judgment basis from IQuickInfoSource.AugmentQuickInfoSession and ITagger.GetTags?
Is there any service could achieve my require? 
How to import services in those case?
Thanks a lot.

**Comment by gundermanc** [comment]
>> I want to highlight the function my assembly implement

Assuming you literally mean highlight them, you can do so by exporting an `ITaggerProvider<TextMarkerTag>` that creates [TextMarkerTags](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.tagging.textmarkertag?view=visualstudiosdk-2017) for each of your assembly's methods.

>> and show a tooltip when mouse hover

Assuming that your assembly is a .NET assembly, you can already provide documentation for your assembly by including an XML documentation file along with your assembly. These docs will be picked up by Roslyn. If you want to add some additional information to the tooltip you can do so by implementing IQuickInfoSourceProvider and returning items for spans of text that contain your assembly's member names.

>> And search all references of my assembly from solution.

This is a more complex task that really can only be done by the language service. Project structure, references, etc. are exposed to the IDE via numerous end points, but AFAIK you have to integrated with the language service to get that kind of info. I'd recommend looking at the Roslyn SDK to see if you can query the Roslyn LS directly. [This code](https://github.com/dotnet/roslyn/tree/master/src/VisualStudio/Core/Def/Implementation/FindReferences) looks related to what you are trying to accomplish. There's probably an API you can consume.

>> Can i get code references,namespace,classname or other judgment basis from IQuickInfoSource.AugmentQuickInfoSession and ITagger.GetTags?

There are probably hacky ways to get this information from Roslyn quick info data or tags produced by Roslyn or the editor but I'd strongly recommend against this. We frequently changing a lot of the underlying structure of editor features and will probably break any extension that depends on impl. details.
