### ISSUE TITLE
version of referenced assemblies

### ISSUE THREAD

**Issue by josesimoes** [Microsoft/VSSDK-Extensibility-Samples#118]
- Visual Studio 15.5.6

### Description
Inside a DeployProvider I'm using this to get the version of the referenced assemblies:
`reference.Metadata.GetEvaluatedPropertyValueAsync("Version")` being `reference` an `IAssemblyReference`
this used to work a few versions back, but now it returns an empty string... anyone know if this has changed ? 

### Current behavior
The above is returning an empty string.

### Expected behavior
Should be returning the version information in the appropriate format: "1.2.3.4"

**Comment by AlexEyler** [comment]
This repo is for the VSSDK samples only. 

For this issue, I would reach out to the CPS team:
Gitter here: https://gitter.im/Microsoft/VSProjectSystem. 
Docs repo here: https://github.com/Microsoft/VSProjectSystem.

You can also log feedback by using the "Report a problem" in Visual Studio (or directly on https://developercommunity.visualstudio.com/spaces/8/index.html).

cc @jviau
