### ISSUE TITLE
Target GenerateFileManifest does not exist during build of MockLanguageExtension

### ISSUE THREAD

**Issue by japj** [microsoft/VSSDK-Extensibility-Samples#150]
### Installed products
- Visual Studio: [Enterprise 15.8.6, Enterprise 15.9 Preview 3]

### Description
Build error in MockLanguageExtension: target GenerateFileManifest does not exist

![image](https://user-images.githubusercontent.com/512/46580382-010c0b00-ca24-11e8-8d6e-a58f8e828bba.png)

The weird thing is that appveyor CI is able to build ok
I also tried installing the latest 15.9 preview with VS Extensibility workload, but I get the same issue.

I did notice there are a fair bit of outdated nuget packages, but since appveyor is ok that should not be a problem right?

### Steps to recreate
1. Clone VSSDK-Extensibility-Samples repository as of 2018-10-03
2. Start either VS 15.8.6 or 15.9 Preview3
3. Open LanguageServerProtocol\MockLanguage.sln
4. Restore Nuget packages
5. Rebuild solution

### Current behavior
Build fails with error: target GenerateFileManifest does not exist

### Expected behavior
Build succeeded

**Comment by saltukkos** [comment]
I have the same issue with BasicSccProvider and restarting the solution fixed this. I noticed that it fails when you start build before the Nuget packages is completely restored and (I assume) MsBuild may cache something wrong information. Some time ago I got quite similar issue on VS 15.8.4 with different project, when only manual editing Reference in .csproj to other value and then reverting to original fixed project building.

**Comment by bcanzanella** [comment]
I recently ran into this as well. Ensuring I had the correct Workloads / Individual components installed from the VS installer fixed it. I'm not 100% sure which additional items fixed it, but I didn't have `.NET Build Tools` -- so it might have been that!

**Comment by dmitry-pavlov** [comment]
Restarting VS2017 as administrator did the trick

**Comment by vnwonah** [comment]
@dmitry-pavlov this worked for me too

**Comment by Kermer** [comment]
I always run VS as admin, but still got this error. Restarting VS fixed it though.

**Comment by ironcev** [comment]
Restarting Visual Studio solves the issue also in VS 2019.

**Comment by ProductiveRage** [comment]
Another worked-for-me-after-restarting instance, this time in VS 2019 Preview (16.5.0 Preview 5.0)

**Comment by sczybt** [comment]
restart and run with administrator.it fixed.
