### ISSUE TITLE
IAsyncCodeLensDataPoint with immediate action without details window

### ISSUE THREAD

**Issue by matkoch** [Microsoft/VSSDK-Extensibility-Samples#156]
The example `CodeLensOopProvider` as well as the existing CodeLens features only show how an additional details window is opened, from where further actions are invoked. Is it possible to execute something just by clicking on a CodeLens `IAsyncCodeLensDataPoint` item?

<img width="648" alt="image" src="https://user-images.githubusercontent.com/5005566/48973190-1374ef00-f03a-11e8-87f2-1ac52bdf76da.png">

**Comment by madskristensen** [comment]
@AmadeusW do you know?

**Comment by AmadeusW** [comment]
I believe that you can't execute an arbitrary command. The API allows you to display string or tabular data in the popup, using [CodeLensDetailsDescriptor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.codelens.remoting.codelensdetailsdescriptor?view=visualstudiosdk-2017).
This class allows you to define [CodeLensDetailPaneCommand](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.codelens.remoting.codelensdetailpanecommand?view=visualstudiosdk-2017)s, perhaps you'll be able to accomplish what you need with this?

Keep in mind that part of the Code Lens API is internal, which means that extensions don't have the same capabilities as default Code Lens items that come with VS.

**Comment by matkoch** [comment]
I understand that, but I wish I could at least do the same as the model in VSCode provides. That is very desirable and from my point of view nothing too complex :)

**Comment by matkoch** [comment]
CodeLensDetailPaneCommand is not really what I’m looking for.
