### ISSUE TITLE
All reference are broken by opening this solution with VS2015 Update1

### ISSUE THREAD

**Issue by gsantopaolo** [Microsoft/VSSDK-Extensibility-Samples#16]
As subject
All reference are broken by opening this solution with VS2015 Update1 and apparently no way of restoring missing packages:
NuGet Package restore failed for project WPFDesigner_XML: Unable to find version '14.0.22823-RC' of package 'Microsoft.VisualStudio.Shell.14.0'
![untitled](https://cloud.githubusercontent.com/assets/9937149/11828623/c8531b34-a396-11e5-9637-f413febc599a.jpg)

**Comment by AlexEyler** [comment]
I'm not able to reproduce this one. Can you check your NuGet Package Manager options in Tools > Options > NuGet Package Manager > Package Sources and make sure nuget.org (https://api.nuget.org/v3/index.json) is checked?

**Comment by gsantopaolo** [comment]
to reproduce the issue
1. download source code at https://github.com/Microsoft/VSSDK-Extensibility-Samples/archive/master.zip
2. unzip it
3. open VSSDK-Extensibility-Samples-master\WPFDesigner_XML\WPFDesigner_XML.sln with visual studio 2015 update 1
4. rebuild the project

You will get the situation reported in the screenshot above.

P.s. just for your information, the error is talking about nugget packages but if you go a bit deeper you will understand that all the broken reference are local references.
I suppose because this project was ported from a previous version of vs to vs 2015 rc but never ported to rtm or rtm update 1.

**Comment by AlexEyler** [comment]
I've followed those steps and I can't reproduce the situation. But it does look like there are some hardcoded HintPaths in there that should be relative:
`C:\Users\v-rokuhl\Source\Repos\VSIDEProj.VSSDKSamples\Samples\Completed_Samples\WPFDesigner_XML\packages\Microsoft.VisualStudio.Validation.14.0.50417-pre\lib\net45\Microsoft.VisualStudio.Validation.dll` should be `..\packages\Microsoft.VisualStudio.Validation.14.0.50417-pre\lib\net45\Microsoft.VisualStudio.Validation.dll`, for example. Let me get a PR with a fix for this to see if that'll help.

**Comment by AlexEyler** [comment]
https://github.com/Microsoft/VSSDK-Extensibility-Samples/pull/17

**Comment by AlexEyler** [comment]
I've merged the PR, can you pull and check again? Make sure that you have the nuget.org option checked in your Nuget Package Manager settings.

**Comment by gsantopaolo** [comment]
Now it works like a charme. Perfect!
