### ISSUE TITLE
How to determine when Visual Studio creates a new WPF window

### ISSUE THREAD

**Issue by xperiandri** [microsoft/VSSDK-Extensibility-Samples#188]
### Installed products
- Visual Studio 2019 16.2

### Description
In order to attach Radial Controller to a window created by Visual Studio I need to know when it was created
See issue https://github.com/madskristensen/DialToolsForVS/issues/18
What is the right event to listen to?

**Comment by tonyhallett** [comment]
[iwpftextviewcreationlistener](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.editor.iwpftextviewcreationlistener?view=visualstudiosdk-2022)

**Comment by xperiandri** [comment]
I used undocumented API
https://github.com/xperiandri/DialControllerTools/blob/7c2cb0b6dffce1a36d41acbb696f98f666d41220/src/DialControllerTools.csproj#L135-L146
and then subscribe to `FloatinWindowManager.FloatingWindowCreated` event
https://github.com/xperiandri/DialControllerTools/blob/7c2cb0b6dffce1a36d41acbb696f98f666d41220/src/Controller/DialControllerHost.cs#L48
