### ISSUE TITLE
Use OnAfterBackgroundSolutionLoadComplete in Solution Load sample

### ISSUE THREAD

**Issue by edgarrs** [microsoft/VSSDK-Extensibility-Samples#191]
The [Solution Load sample](https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/SolutionLoadEvents) uses the event OnAfterOpenSolution to detect when the solution has completed loading but OnAfterBackgroundSolutionLoadComplete is the final event in the solution load flow, so it is the one that should be used.

**Comment by madskristensen** [comment]
Fixed
