### ISSUE TITLE
Add a sample for analyzer/codefix

### ISSUE THREAD

**Issue by JohanLarsson** [microsoft/VSSDK-Extensibility-Samples#195]
When writing analyzers it can be useful to have a vsix for debugging and for testing things before releasing nugets.

It would be nice with a sample with up-to-date best practices.

I don't know enough about VSIX to contribute it but if someone does I can add a simple analyzer & fix.

**Comment by JohanLarsson** [comment]
Forgot about the analyzer template project in VS. Maybe it is good enough, this issue can be closed if you feel it is.

**Comment by mrlacey** [comment]
I've always found the one that is created from the built-in template to be sufficient.
