### ISSUE TITLE
Microsoft.VisualStudio.SDK package should probably not have a dependency on Microsoft.VisualStudio.DpiAwareness

### ISSUE THREAD

**Issue by gfraiteur** [microsoft/VSSDK-Extensibility-Samples#214]
### Installed products
- Microsoft.VisualStudio.SDK 16.0.200

### Description

It seems that Microsoft.VisualStudio.DpiAwareness is obsolete and contains only type forwarders to Microsoft.VisualStudio.Utilities. However it is still included in the SDK package.

It makes it impossible to reference anything included in Microsoft.VisualStudio.DpiAwareness  because of CS0433.

### Current behavior
error CS0433: The type 'DpiAwareness' exists in both 'Microsoft.VisualStudio.DpiAwareness, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'Microsoft.VisualStudio.Utilities, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 

### Expected behavior
Referencing DpiAwareness should work without compilation error.

**Comment by madskristensen** [comment]
Thanks @gfraiteur. Could you please report the same issue using Send Feedback inside Visual Studio? Then it goes straight to the extensibility engineering team. Thanks, and sorry for the inconvenience.

**Comment by gfraiteur** [comment]
Done.
