### ISSUE TITLE
`[Export(typeof(ICodeLensCallbackListener))]` not working?

### ISSUE THREAD

**Issue by bert2** [microsoft/VSSDK-Extensibility-Samples#215]
I'm trying to write a CodeLens extension for Visual Studio 2019, but I'm unable to register and remote-call my `ICodeLensCallbackListener`.

Since there is almost no documentation on the `ICodeLensCallbackListener` interface, I've been digging through the Visual Studio source code and found the [`CodeLensCallbackListener`](https://github.com/dotnet/roslyn/blob/438047c55d476191fc5cb3df5f02925418139f1d/src/VisualStudio/Core/Def/Implementation/CodeLens/CodeLensCallbackListener.cs#L33) which is called remotely by the [`ReferenceCodeLensProvider.DataPoint`](https://github.com/dotnet/roslyn/blob/30b18ba60e11d358425732e52ec3061deeb01105/src/VisualStudio/CodeLens/ReferenceCodeLensProvider.cs#L155) class.

I basically copied & pasted that code:

My package class:

```csharp
[PackageRegistration(UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
[InstalledProductRegistration("#100", "#101", "ede7ef0f-017b-4b33-b7b3-c7480d3cc712", IconResourceID = 400)]
[Guid(PackageGuidString)]
[ProvideAutoLoad(UIContextGuids80.SolutionExists, PackageAutoLoadFlags.BackgroundLoad)]
public sealed class MicroscopePackage : AsyncPackage {
    public const string PackageGuidString = "b798b46c-201a-470c-9e3e-fa0abb23dfa7";
    public MicroscopePackage() {
        Log(); // this is being hit
    }
}
```

My callback listener in the same assembly where the package class is located:

```csharp
[Export(typeof(ICodeLensCallbackListener))]
[ContentType("CSharp")]
public class CodeLensCallbackListener : ICodeLensCallbackListener, ICodeLensContext {
    [ImportingConstructor]
    public CodeLensCallbackListener() {
        try {
            Log(); // this is never being hit
        } catch (System.Exception ex) {
            Log(ex);
            throw;
        }
    }

    public int Foo() {
        try {
            Log(); // not being hit either of course
            return 42;
        } catch (System.Exception ex) {
            Log(ex);
            throw;
        }
    }
}
```

Inside my `IAsyncCodeLensDataPoint` implementation I'm trying to call the callback listener like so:

```csharp
public async Task<CodeLensDataPointDescriptor> GetDataAsync(CodeLensDescriptorContext descriptorContext, CancellationToken token) {
    try {
        Log();

       // this fails with a `StreamJsonRpc.RemoteMethodNotFoundException`
        var foo = await callbackService
            .InvokeAsync<int>(this, nameof(ICodeLensContext.Foo), cancellationToken: token)
            .ConfigureAwait(false);
        Log(foo);

        return new CodeLensDataPointDescriptor { ... };
    } catch (Exception ex) {
        Log(ex);
        throw;
    }
}
```

But this always fails with an exception:

>StreamJsonRpc.RemoteMethodNotFoundException: No method by the name 'Foo' is found.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__118'1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable'1.ConfiguredTaskAwaiter.GetResult()
   at Microscope.CodeLensProvider.ILDataPoint.<GetDataAsync>d__8.MoveNext()

I assume that's because my `ICodeLensCallbackListener` is never being picked up by MEF. Am I exporting it incorrectly?

The project is hosted [here](https://github.com/bert2/microscope/tree/master/src) if you wanna have a look at the full source.

In case context is relevant: I want to provide the IL instructions of a code-lensed member to Visual Studio. In order not to re-create the `Workspace` & project `Compilation` out-of-process with my `IAsyncCodeLensDataPointProvider`, I want to callback into Visual Studio and use the `Compilation` available there for free to emit IL instructions. The callback listener then sends those back to the CodeLens provider.

**Comment by bert2** [comment]
I was able to resolve this problem by clearing MEF's cache as described in [another issue](https://github.com/github/VisualStudio/issues/1859): I simply deleted both `16.0_91e26d90Exp\Extensions\extensions.en-US.cache` and `16.0_91e26d90Exp\ComponentModelCache\`.

**Comment by thedemons** [comment]
Note that `[ContentType("any")]` doesn't work. It took me ages to figure that out, when it works for basically anything else. Here is the list of all the currently supported languages:
```cs
[ContentType("C/C++")]
[ContentType("CSharp")]
[ContentType("Basic")]
[ContentType("vbscript")]
[ContentType("TypeScript")]
[ContentType("JavaScript")]
```
