### ISSUE TITLE
Intra-text_Adornment readme is full of spacing mistakes

### ISSUE THREAD

**Issue by mrb113** [Microsoft/VSSDK-Extensibility-Samples#28]
[Intra-Text Adornment's README.md](https://github.com/Microsoft/VSSDK-Extensibility-Samples/blob/8de2e04f6d1e72a0d818108d8d10558effdd3c01/Intra-text_Adornment/Readme.md) looks like it was copy/pasted from somewhere and spacing errors were never resolved.

- *F5or choose the *Debug > Start Debuggingmenu command.  
- comment out the line**#define HIDING_TEXTin ColorAdornmentTagger.cs.

**Comment by timsneath** [comment]
Thanks - fixed.
