### ISSUE TITLE
Is it possible to access the VS graphical resources?

### ISSUE THREAD

**Issue by Cybrosys** [Microsoft/VSSDK-Extensibility-Samples#40]
Is it possible to access the Visual Studio graphical resources (toolbar icons, ...) when creating your own WPF UserControl / ToolWindow?

**Update**
Found "Visual Studio Image Library" here:
https://www.microsoft.com/en-us/download/details.aspx?id=35825

**Comment by IInspectable** [comment]
And don't forget to read this [Image Service and Catalog](https://msdn.microsoft.com/en-us/library/mt628927.aspx). ;-)
