### ISSUE TITLE
WPFDesigner_XML example doesn't work in VS 2017 (Community)

### ISSUE THREAD

**Issue by Styxxy** [microsoft/VSSDK-Extensibility-Samples#61]
### Installed products
- Visual Studio: Community 2017 (15.1)

### Description
I try running the WPFDesigner_XML example in Visual Studio 2017. However I am not able to run this sample. After changing the .NET version and adding prerequisites to the vsix manifest, I get a build error on the reference Microsoft.VisualStudio.XmlEditor (it cannot find this reference).

I don't find this assembly anywhere in "Add Reference" window nor on Nuget.

**Comment by Styxxy** [comment]
After manually adding a reference to "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Xml\Microsoft.VisualStudio.XmlEditor.dll" the project runs.

However, I have a feeling that this is not a really good solution.

**Comment by RayKoopa** [comment]
I also just wondered why some assemblies aren't available in NuGet, but others are, is that a licensing problem or why is everything so bogus about the assembly sources?
