### ISSUE TITLE
IronPythonStudio-Integrated has missing files

### ISSUE THREAD

**Issue by setterst** [Microsoft/VSSDK-Extensibility-Samples#9]
The project currently doesn't build due to a missing project file for 'IronPython.EditorExtensions'.  

There are also numerous files using types from the IronPython.Hosting namespace, but I cannot find any types defined in that namespace.

**Comment by SelmaI** [comment]
Hi Setterst,
thank you for filing the issue. We decided not to support IronPython sample, as https://github.com/dotnet/roslyn is a complete and up to date language sample.
Thanks,
Selma

**Comment by setterst** [comment]
Selma,

Thank you for the reply.

Do you have any suggestions for another sample that would demonstrate interacting with the built in Windows Forms or WPF/XAML editors?

Regards,
Sean

**Comment by SelmaI** [comment]
Sean, the sample is available for previous versions of VS here: https://code.msdn.microsoft.com/windowsdesktop/IronPython-Integrated-Shell-0b71ce53#content, you may look at that.
In our backlog, i included an item to create samples that shows interacting with the built in Windows Forms , WPF/XAML editors.
Thanks,
--Selma
