### ISSUE TITLE
Menu_And_Commands sample has incorrectly named file Example.MenusAndCommands.png

### ISSUE THREAD

**Issue by mikehadlow** [Microsoft/VSSDK-Extensibility-Samples#99]
### Installed products
- Visual Studio Community 2017 Version 15.3.5

### Description
The Menu_And_Commands sample has an incorrectly named file:
Example.MenusAndCommands.png
Should be:
Example.MenuAndCommands.png (singular 'Menu' not 'Menus')

### Steps to recreate
Clone sample and build.

### Current behavior
Build fails with: "Could not copy the file "C:\Source\VSSDK-Extensibility-Samples\Menu_And_Commands\C#\Example.MenuAndCommands.png" because it was not found."

### Expected behavior
Sample should build correctly.

#### Notes
The solution built after I renamed the file as described above.

**Comment by StephanieSu** [comment]
Fixed.  Thanks for reporting!
